import pandas as pd
import numpy as np
import random
from sklearn.metrics import f1_score
from sklearn.neural_network import MLPClassifier

def create_model():
    """
    This function creates an instance of the MLPClassifier model with a fixed structure.
    One hidden layer with 10 neurons.
    Only one iteration just to initialize the weights.
    """
    return MLPClassifier(
        hidden_layer_sizes=(10,),
        max_iter = 1,
        random_state=42
    )

def initialize_model(model, X_train, y_train):
    """
    This function initializates the model to our data, creating the internal structure of weights and biases and assigning the initial values for them.

    Parameters:
    - model: the MLP classifier from create_model function.
    - X_train -> DataFrame: The data on which the model will be initialized.
    - y_train -> Series: The labels of the training data.

    --------------
    Output:
    - model: The model with the structure defined.
    """
    model.fit(X_train, y_train)

    return model

def get_solution_size(model):
    """
    A solution is a vector of weights and biases. This functions gets the total size of a solution, by adding the weights and biases.

    Parameters:
    - model:  The model with the structure defined.

    -------------
    Output:
    - total_size -> int: The length that the solutions must have.
    """
    total_size = 0

    for coef_matrix in model.coefs_:
        total_size += coef_matrix.size
    
    for bias_vector in model.intercepts_:
        total_size += bias_vector.size

    return total_size
    
def generate_solution_uniform(size, lower_bound, upper_bound):
    """
    This functions generates a vector of size established in the function above, where each element is a random float between the boundaries.

    Parameters:
    - size -> int: Size of the vector, it is equal to the toal number of weights and biases in the network
    - lower_bound -> float: Defines the minimum.
    - higher_bound -> float: Defines the maximum

    -------------
    Output:
    - solution -> list: Vector with weights and biases
    """
    
    return [random.uniform(lower_bound,upper_bound) for _ in range(size)]

def generate_solution_gaussian(size, mean = 0, sigma = 1):
    """
    This functions generates a vector of size established in the function above, where each element is a number of a gaussian distribution

    Parameters:
    - size -> int: Size of the vector, it is equal to the toal number of weights and biases in the network
    - mean -> float: The center of the distribution.
    - sigma-> float: The standard deviation of the distribution. Controls how spread out the values are related to the mean.

    -------------
    Output:
    - solution -> list: Vector with weights and biases
    """  

    return [random.gauss(mean, sigma) for _ in range(size)]

def set_weights(model, solution):
    """
    This is the function that inserts a candidate solution generated by the GA/PSO into the neural network.
    At the beginning, this solution is random. After the optimization process, it can be the best optimized solution.

    Parameters:
    - model: The model with the structure defined.
    - solution -> list: The vector of weights and biases generated by the GA/PSO inserted into the neural network.
    """
    idx = 0

    for i in range(len(model.coefs_)):
        shape = model.coefs_[i].shape
        size = model.coefs_[i].size

        values = solution[idx:idx + size]
        model.coefs_[i] = np.array(values).reshape(shape)

        idx += size

    for i in range(len(model.intercepts_)):
        shape = model.intercepts_[i].shape
        size = model.intercepts_[i].size

        values = solution[idx:idx + size]
        model.intercepts_[i] = np.array(values).reshape(shape)

        idx += size

def fitness_function(solution, model, X, y):
    """
    This function evaluates the fitness of a candidate solution.

    In this project, a solution is a vector containing all the weights and biases of the neural network. 
    Since MLPClassifier stores these parameters in matrices and vectors, the solution is first reshaped and loaded into the model using set_weights().

    After setting the weights, the model makes predictions on the training data. 
    The quality of the solution is then measured using the chosen performance metric, implemented in evaluate_performance().

    Parameters:
    - solution -> list: The vector of weights and biases.
    - model: The model with the structure defined.
    - X -> Input data used to evaluate the candidate solution.
    - y -> True labels corresponding to X.

    Output:
    - score: Fitness score of the candidate solution, computed as macro F1-score.
    """

    set_weights(model, solution)

    y_pred = model.predict(X)
    score = f1_score(y, y_pred, average='macro', zero_division=0)

    return score
